org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.162
neo_version_range=[21.1.162,)
loader_version_range=[1,)

## Mod Properties

mod_id=turtlechargingstation
mod_name=Turtle Charging Station
mod_license=MIT License
mod_version=1.7.0-beta

mod_group_id=com.mikitellurium.turtlechargingstation
mod_authors=Miki Tellurium
mod_description=Recharge CC:Tweaked turtles using Forge Energy.

# Dependencies
cc_version=1.115.1
telluriumforge_version= 1.4.0
jei_version=19.21.0.247
mekanism_version=10.7.14.79
thermal_version=
powah_version=6.2.4
cloth_config_version=15.0.140
architectury_version=13.0.8
guideme_version=21.1.8