org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2
forge_version=14.23.5.2860

mapping_channel=stable
mapping_version=39-1.12

mod_id=turtlechargingstation
mod_name=Turtle Charging Station

mod_license=MIT

mod_version=1.7.1-beta

mod_group_id=com.mikitellurium.turtlechargingstation
mod_authors=Miki Tellurium
mod_description=Recharge CC:Tweaked turtles using Forge Energy <----Change this.
mod_icon=turtlechargingstationlogo.png
mod_url=https://modrinth.com/mod/turtle-charging-station

# Dependencies
cc_version=1.89.2
telluriumforge_version= 1.4.0
jei_version=4.16.1.302

mekanism_version=10.7.14.79
thermal_version=
powah_version=6.2.4
cloth_config_version=15.0.140
architectury_version=13.0.8
guideme_version=21.1.8
