package com.mikitellurium.turtlechargingstation.config;

import com.mikitellurium.telluriumforge.config.TelluriumConfig;
import com.mikitellurium.turtlechargingstation.TurtleChargingStationMod;
import com.mikitellurium.turtlechargingstation.common.blockentity.ThunderchargeDynamoBlockEntity;
import com.mikitellurium.turtlechargingstation.common.blockentity.TurtleChargingStationBlockEntity;
import com.mikitellurium.turtlechargingstation.util.FastId;

public class ModConfig {
    private static final TelluriumConfig COMMON_CONFIG = new TelluriumConfig(FastId.modId(), TelluriumConfig.Type.COMMON);

    public static void register() {
        setupConfig(COMMON_CONFIG);
    }

    private static void setupConfig(TelluriumConfig config) {
        config.comment("Turtle Charging Station Configuration");

        TurtleChargingStationBlockEntity.CAPACITY = config.entryBuilder()
                .defineInRange("chargingStationMaxCapacity", 64000, 0, (long)Integer.MAX_VALUE)
                .comment("The maximum amount of energy the charging station can hold");
        TurtleChargingStationBlockEntity.CONVERSION_RATE = config.entryBuilder()
                .defineInRange("chargingStationConversionRate", 256, 0, (long)Integer.MAX_VALUE)
                .comment("The amount of energy required to increase the turtle fuel level by 1");
        ThunderchargeDynamoBlockEntity.RECHARGE_AMOUNT = config.entryBuilder()
                .defineInRange("dynamoRechargeAmount", 1200, 0, Integer.MAX_VALUE)
                .comment("The amount of time (in ticks) that is added to the charge when the thundercharge")
                .comment("dynamo is struck by lightning.")
                .comment("# 1 minute = 1200 in-game ticks");
        ThunderchargeDynamoBlockEntity.TRANSFER_RATE = config.entryBuilder()
                .defineInRange("dynamoTransferRate", 1024, 0, (long)Integer.MAX_VALUE)
                .comment("The amount of energy per tick generated by the thundercharge dynamo");

        config.build();
    }

    public static TelluriumConfig getCommon() {
        return COMMON_CONFIG;
    }
}
