package com.mikitellurium.turtlechargingstation.config;

import com.mikitellurium.turtlechargingstation.TurtleChargingStationMod;
import com.mikitellurium.turtlechargingstation.blockentity.ThunderchargeDynamoBlockEntity;
import com.mikitellurium.turtlechargingstation.blockentity.TurtleChargingStationBlockEntity;
import net.neoforged.fml.ModLoadingContext;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.ModConfigSpec;

public class ModConfigs {

    public static void register() {
        ModConfigSpec spec = setupConfig();
        ModLoadingContext.get().getActiveContainer().registerConfig(ModConfig.Type.COMMON, spec);
    }

    public static ModConfigSpec setupConfig() {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        builder.comment("Turtle Charging Station Configuration").push(TurtleChargingStationMod.MOD_ID);

        TurtleChargingStationBlockEntity.CAPACITY = builder
                .comment("The maximum amount of FE the charging station can hold")
                .defineInRange("chargingStationMaxCapacity", 64000, 0, Integer.MAX_VALUE);
        TurtleChargingStationBlockEntity.CONVERSION_RATE = builder
                .comment("The amount of FE required to increase the turtle fuel level by 1")
                .defineInRange("chargingStationConversionRate", 256, 0, Integer.MAX_VALUE);
        ThunderchargeDynamoBlockEntity.RECHARGE_AMOUNT = builder
                .comment("The amount of time (in ticks) that is added to the thundercharge dynamo charge.",
                        "1 minute = 1200 in-game ticks")
                .defineInRange("dynamoRechargeAmount", 1200, 0, Integer.MAX_VALUE);
        ThunderchargeDynamoBlockEntity.TRANSFER_RATE = builder
                .comment("The amount of FE/tick generated by the thundercharge dynamo")
                .defineInRange("dynamoTransferRate", 1024, 0, Integer.MAX_VALUE);

        builder.pop();
        return builder.build();
    }

}
