package com.mikitellurium.turtlechargingstation.config;

import com.mikitellurium.turtlechargingstation.TurtleChargingStationMod;
import com.mikitellurium.turtlechargingstation.common.blockentity.ThunderchargeDynamoBlockEntity;
import com.mikitellurium.turtlechargingstation.common.blockentity.TurtleChargingStationBlockEntity;
import net.neoforged.fml.ModLoadingContext;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.neoforge.common.ModConfigSpec;

public class ModConfigs {
    private static ModConfigSpec COMMON_CONFIG;

    public static void register() {
        COMMON_CONFIG = setupConfig();
        ModLoadingContext.get().getActiveContainer().registerConfig(ModConfig.Type.COMMON, COMMON_CONFIG);
    }

    public static ModConfigSpec setupConfig() {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        builder.comment("Turtle Charging Station Configuration").push(TurtleChargingStationMod.MOD_ID);

        TurtleChargingStationBlockEntity.CAPACITY = builder
                .comment("The maximum amount of FE the charging station can hold.")
                .defineInRange("chargingStationMaxCapacity", 64000, 0, Integer.MAX_VALUE);
        TurtleChargingStationBlockEntity.CONVERSION_RATE = builder
                .comment("The amount of FE required to increase the turtle fuel level by 1.")
                .defineInRange("chargingStationConversionRate", 256, 0, Integer.MAX_VALUE);
        ThunderchargeDynamoBlockEntity.RECHARGE_AMOUNT = builder
                .comment("The amount of time (in ticks) that is added to the charge when the thundercharge",
                        "dynamo is struck by lightning.",
                        "1 minute = 1200 in-game ticks")
                .defineInRange("dynamoRechargeAmount", 1200, 0, Integer.MAX_VALUE);
        ThunderchargeDynamoBlockEntity.TRANSFER_RATE = builder
                .comment("The amount of FE/tick generated by the thundercharge dynamo.")
                .defineInRange("dynamoTransferRate", 1024, 0, Integer.MAX_VALUE);

        builder.pop();
        return builder.build();
    }

    public static ModConfigSpec getCommon() {
        return COMMON_CONFIG;
    }
}
